version: '3'

services:
  centos:
    build:
      context: .
      dockerfile: Dockerfile-sign-centos
    volumes:
      - gnupg_centos:/root/.gnupg
      - ./build:/build
      - ./support:/support

  debian:
    build:
      context: .
      dockerfile: Dockerfile-sign-debian
    volumes:
      - gnupg_debian:/root/.gnupg
      - ./build:/build

volumes:
  gnupg_centos:
  gnupg_debian:
